AWS_ACCESS_KEY_ID_MEND = " AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY_MEND = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

AWS_ACCESS_KEY_ID_MEND = " AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY_MEND = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"


